### ISSUE TITLE
SHA2(56)

### ISSUE THREAD

**Issue by druhimself** [eduardsui/ISUToCNP#1]
Pentru ISU este utilizat SHA256. Nu îmi dau seama acum daca schimba cu ceva datele din/in raportarea ta

**Comment by eduardsui** [comment]
Conform datelor cerute de ANCOM, functia folosita este sha1. De asemena, sha1 este confirmat si de ei telefonic. Pot folosi orice sha(1-3), vulnerabilitatea nu este legata de functia in sine ci de felul in care este folosita.

**Comment by cristianst85** [comment]
> Pentru ISU este utilizat SHA256. Nu îmi dau seama acum daca schimba cu ceva datele din/in raportarea ta

Poți posta o sursă/link pentru afirmația asta?

SHA-1 produce un rezultat cu o lungime de 40 de caractere alfanumerice (în format hexadecimal).
SHA-256 produce un rezultat cu o lungime de 64 de caractere alfanumerice (în format hexadecimal).

Potrivit [acestui](https://www.recensamantromania.ro/wp-content/uploads/2022/02/HG-144-plus-anexelev3.pdf) document, ISU (Identificator Statistic Unic) e definit ca fiind de tipul numeric și având o lungime de 40. Ce mi se pare ciudat e că în documentația lor ISU e definit ca fiind _numeric_ în loc de _alfanumeric_, dar asta ar putea fi o simplă greșeală.

**Comment by eduardsui** [comment]
Functiile shaX produc biti. Acei biti reprezinta un numar. Pentru a putea reprezenta acel numar ca text, se uneori reprezentarea text-baza16, alteori baza64.

**Comment by cristianst85** [comment]
Acele tipuri de date din tabel sunt specifice bazelor de date Oracle (vezi varchar2). E posibil într-adevăr ca Oracle să stocheze acel câmp direct în format numeric.

**Comment by eduardsui** [comment]
Acum m-am prins. Scuze, ignora reply-ul anterior. Ei practic considera ISU reprezentarea alfa numerica a output-ului sha, nu valoarea numerica in sine.

**Comment by cristianst85** [comment]
> Acum m-am prins. Scuze, ignora reply-ul anterior. Ei practic considera ISU reprezentarea alfa numerica a output-ului sha, nu valoarea numerica in sine.

No problem. Primul meu mesaj era adresat lui @druhimself.

**Comment by eduardsui** [comment]
![Uploading 5E62D019-F4C4-49A8-80D3-1E8D78ACBD9E.jpeg…]()

**Comment by eduardsui** [comment]
Am adaugat un screnshot din documentatie direct in repository. Am folosit(de lene) direct telefonul.

**Comment by carco** [comment]
> Am adaugat un screnshot din documentatie direct in repository. Am folosit(de lene) direct telefonul.

Despre ce documentatie e vorba / e publica sau e "pe surse"? Exista undeva, public, un document oficial care spune clar ca ala e algoritmul folosit? In acea documentatie pare un exemplu (cum ar putea fi obtinut un identificator).

**Comment by eduardsui** [comment]
A fost publica documentatia pe site-ul ANCOM. A fost data jos in jur de 5 aprilie.
